version: '3'
services:
  elasticsearch-srv:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch-host
    environment:
      - discovery.type=single-node
      #- ELASTICSEARCH_USERNAME=elastic
      - xpack.security.enabled= true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=elastic
    volumes:
      - C:\\work\\elasticVolum\\elastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"


  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-host:9200
      #- XPACK_SECURITY_ENABLED= "true"
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=elastic
    volumes:
      - C:\\work\\elasticVolum\\kibana:/usr/share/kibana/data
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch-srv

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.1
    container_name: logstash
    environment:
      - xpack.monitoring.elasticsearch.hosts=http://elasticsearch-host:9200
      #- ELASTICSEARCH_USERNAME=logstash_system
      #- ELASTICSEARCH_PASSWORD=elastic
      #- ELASTIC_USERNAME=elastic
      #- ELASTIC_PASSWORD=elastic
      - xpack.monitoring.elasticsearch.username=logstash_system
      - xpack.monitoring.elasticsearch.password=elastic
      - xpack.monitoring.enabled=true
    volumes:
      - C:\\work\\elasticVolum\\logstash\\pipeline:/usr/share/logstash/pipeline
      - C:\\work\\elasticVolum\\logstash\\config:/usr/share/logstash/config
      - C:\\work\\elasticVolum\\logstash\\plugins:/usr/share/logstash/plugins
      - C:\\work\\elasticVolum\\logstash\\logs:/var/log
    ports:
      - "5000:5000"
      - "9600:9600"
    depends_on:
      - elasticsearch-srv

  